"""Implementation of statechart statechart.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))
from .yakindu.rx import Observable

class Statechart:
	"""Implementation of the state machine Statechart.
	"""

	class State:
		""" State Enum
		"""
		(
			constituent_lifecycle_orthogonal_states,
			constituent_lifecycle_orthogonal_states_belonging_disengaged,
			constituent_lifecycle_orthogonal_states_belonging_prepared,
			constituent_lifecycle_orthogonal_states_belonging_passive,
			constituent_lifecycle_orthogonal_states_belonging_active,
			constituent_lifecycle_orthogonal_states_health_ideal,
			constituent_lifecycle_orthogonal_states_health_defective,
			constituent_lifecycle_orthogonal_states_health_faulty,
			constituent_lifecycle_orthogonal_states_health_erroneous,
			constituent_lifecycle_orthogonal_states_health_malfunctioning,
			constituent_lifecycle_orthogonal_states_health_degraded,
			constituent_lifecycle_orthogonal_states_health_failed,
			null_state
		) = range(13)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.belong_id = None
		self.health_id = None
		self.prepare_for_so_s = None
		self.disengage_from_so_s = None
		self.join_so_s = None
		self.leave_so_s = None
		self.join_constellation = None
		self.leave_constellation = None
		self.recovery = None
		self.component_deviation = None
		self.defect_activated = None
		self.fault_exercised = None
		self.error_propogation = None
		self.service_impact_observed = None
		self.service_threshold_violated = None
		self.announce = None
		self.announce_value = None
		self.announce_observable = Observable()
		
		self.__internal_event_queue = queue.Queue()
		self.in_event_queue = queue.Queue()
		self.JS = "join_SoS"
		self.LS = "leave_SoS"
		self.JC = "join_constellation"
		self.LC = "leave_constellation"
		self.DISENGAGED_ID = 1
		self.PREPARED_ID = 2
		self.PASSIVE_ID = 3
		self.ACTIVE_ID = 4
		self.IDEAL_ID = 1
		self.DEFECTIVE_ID = 2
		self.FAULTY_ID = 3
		self.ERRONEOUS_ID = 4
		self.MALFUNC_ID = 5
		self.DEGRADED_ID = 6
		self.FAILED_ID = 7
		self.health_changed = None
		
		# enumeration of all states:
		self.__State = Statechart.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 2
		for __state_index in range(2):
			self.__state_vector[__state_index] = self.State.null_state
		
		# initializations:
		#Default init sequence for statechart Statechart
		self.belong_id = 0
		self.health_id = 0
		self.__is_executing = False
		self.__state_conf_vector_position = None
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.constituent_lifecycle_orthogonal_states:
			return (self.__state_vector[0] >= self.__State.constituent_lifecycle_orthogonal_states)\
				and (self.__state_vector[0] <= self.__State.constituent_lifecycle_orthogonal_states_health_failed)
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_disengaged
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_prepared
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_active:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_active
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_ideal:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_ideal
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_defective:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_defective
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_faulty:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_faulty
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_erroneous:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_erroneous
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_malfunctioning
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_degraded:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_degraded
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_failed:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_failed
		return False
		
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.__internal_event_queue.empty():
			return self.__internal_event_queue.get()
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_health_changed(self):
		"""Raise method for event health_changed.
		"""
		self.__internal_event_queue.put(self.__raise_health_changed_call)
	
	def __raise_health_changed_call(self):
		"""Raise callback for event health_changed.
		"""
		self.health_changed = True
	
	def raise_prepare_for_so_s(self):
		"""Raise method for event prepare_for_so_s.
		"""
		self.in_event_queue.put(self.__raise_prepare_for_so_s_call)
		self.run_cycle()
	
	def __raise_prepare_for_so_s_call(self):
		"""Raise callback for event prepare_for_so_s.
		"""
		self.prepare_for_so_s = True
	
	def raise_disengage_from_so_s(self):
		"""Raise method for event disengage_from_so_s.
		"""
		self.in_event_queue.put(self.__raise_disengage_from_so_s_call)
		self.run_cycle()
	
	def __raise_disengage_from_so_s_call(self):
		"""Raise callback for event disengage_from_so_s.
		"""
		self.disengage_from_so_s = True
	
	def raise_join_so_s(self):
		"""Raise method for event join_so_s.
		"""
		self.in_event_queue.put(self.__raise_join_so_s_call)
		self.run_cycle()
	
	def __raise_join_so_s_call(self):
		"""Raise callback for event join_so_s.
		"""
		self.join_so_s = True
	
	def raise_leave_so_s(self):
		"""Raise method for event leave_so_s.
		"""
		self.in_event_queue.put(self.__raise_leave_so_s_call)
		self.run_cycle()
	
	def __raise_leave_so_s_call(self):
		"""Raise callback for event leave_so_s.
		"""
		self.leave_so_s = True
	
	def raise_join_constellation(self):
		"""Raise method for event join_constellation.
		"""
		self.in_event_queue.put(self.__raise_join_constellation_call)
		self.run_cycle()
	
	def __raise_join_constellation_call(self):
		"""Raise callback for event join_constellation.
		"""
		self.join_constellation = True
	
	def raise_leave_constellation(self):
		"""Raise method for event leave_constellation.
		"""
		self.in_event_queue.put(self.__raise_leave_constellation_call)
		self.run_cycle()
	
	def __raise_leave_constellation_call(self):
		"""Raise callback for event leave_constellation.
		"""
		self.leave_constellation = True
	
	def raise_recovery(self):
		"""Raise method for event recovery.
		"""
		self.in_event_queue.put(self.__raise_recovery_call)
		self.run_cycle()
	
	def __raise_recovery_call(self):
		"""Raise callback for event recovery.
		"""
		self.recovery = True
	
	def raise_component_deviation(self):
		"""Raise method for event component_deviation.
		"""
		self.in_event_queue.put(self.__raise_component_deviation_call)
		self.run_cycle()
	
	def __raise_component_deviation_call(self):
		"""Raise callback for event component_deviation.
		"""
		self.component_deviation = True
	
	def raise_defect_activated(self):
		"""Raise method for event defect_activated.
		"""
		self.in_event_queue.put(self.__raise_defect_activated_call)
		self.run_cycle()
	
	def __raise_defect_activated_call(self):
		"""Raise callback for event defect_activated.
		"""
		self.defect_activated = True
	
	def raise_fault_exercised(self):
		"""Raise method for event fault_exercised.
		"""
		self.in_event_queue.put(self.__raise_fault_exercised_call)
		self.run_cycle()
	
	def __raise_fault_exercised_call(self):
		"""Raise callback for event fault_exercised.
		"""
		self.fault_exercised = True
	
	def raise_error_propogation(self):
		"""Raise method for event error_propogation.
		"""
		self.in_event_queue.put(self.__raise_error_propogation_call)
		self.run_cycle()
	
	def __raise_error_propogation_call(self):
		"""Raise callback for event error_propogation.
		"""
		self.error_propogation = True
	
	def raise_service_impact_observed(self):
		"""Raise method for event service_impact_observed.
		"""
		self.in_event_queue.put(self.__raise_service_impact_observed_call)
		self.run_cycle()
	
	def __raise_service_impact_observed_call(self):
		"""Raise callback for event service_impact_observed.
		"""
		self.service_impact_observed = True
	
	def raise_service_threshold_violated(self):
		"""Raise method for event service_threshold_violated.
		"""
		self.in_event_queue.put(self.__raise_service_threshold_violated_call)
		self.run_cycle()
	
	def __raise_service_threshold_violated_call(self):
		"""Raise callback for event service_threshold_violated.
		"""
		self.service_threshold_violated = True
	
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_disengaged(self):
		"""Entry action for state 'Disengaged'..
		"""
		#Entry action for state 'Disengaged'.
		self.belong_id = self.DISENGAGED_ID
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_prepared(self):
		"""Entry action for state 'Prepared'..
		"""
		#Entry action for state 'Prepared'.
		self.belong_id = self.PREPARED_ID
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Entry action for state 'Passive'..
		"""
		#Entry action for state 'Passive'.
		self.belong_id = self.PASSIVE_ID
		self.announce_observable.next(self.JS)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Entry action for state 'Active'..
		"""
		#Entry action for state 'Active'.
		self.belong_id = self.ACTIVE_ID
		self.announce_observable.next(self.JC)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_ideal(self):
		"""Entry action for state 'Ideal'..
		"""
		#Entry action for state 'Ideal'.
		self.health_id = self.IDEAL_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_defective(self):
		"""Entry action for state 'Defective'..
		"""
		#Entry action for state 'Defective'.
		self.health_id = self.DEFECTIVE_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_faulty(self):
		"""Entry action for state 'Faulty'..
		"""
		#Entry action for state 'Faulty'.
		self.health_id = self.FAULTY_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_erroneous(self):
		"""Entry action for state 'Erroneous'..
		"""
		#Entry action for state 'Erroneous'.
		self.health_id = self.ERRONEOUS_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_malfunctioning(self):
		"""Entry action for state 'Malfunctioning'..
		"""
		#Entry action for state 'Malfunctioning'.
		self.health_id = self.MALFUNC_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_degraded(self):
		"""Entry action for state 'Degraded'..
		"""
		#Entry action for state 'Degraded'.
		self.health_id = self.DEGRADED_ID
		self.raise_health_changed()
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_failed(self):
		"""Entry action for state 'Failed'..
		"""
		#Entry action for state 'Failed'.
		self.health_id = self.FAILED_ID
		self.raise_health_changed()
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Exit action for state 'Passive'..
		"""
		#Exit action for state 'Passive'.
		self.announce_observable.next(self.LS)
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Exit action for state 'Active'..
		"""
		#Exit action for state 'Active'.
		self.announce_observable.next(self.LC)
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_default(self):
		"""'default' enter sequence for state Orthogonal States.
		"""
		#'default' enter sequence for state Orthogonal States
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_default()
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default(self):
		"""'default' enter sequence for state Disengaged.
		"""
		#'default' enter sequence for state Disengaged
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_disengaged()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default(self):
		"""'default' enter sequence for state Prepared.
		"""
		#'default' enter sequence for state Prepared
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_prepared()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_prepared
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default(self):
		"""'default' enter sequence for state Passive.
		"""
		#'default' enter sequence for state Passive
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_passive
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active_default(self):
		"""'default' enter sequence for state Active.
		"""
		#'default' enter sequence for state Active
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_active()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default(self):
		"""'default' enter sequence for state Ideal.
		"""
		#'default' enter sequence for state Ideal
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_ideal()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_ideal
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_defective_default(self):
		"""'default' enter sequence for state Defective.
		"""
		#'default' enter sequence for state Defective
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_defective()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_defective
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_faulty_default(self):
		"""'default' enter sequence for state Faulty.
		"""
		#'default' enter sequence for state Faulty
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_faulty()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_faulty
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_erroneous_default(self):
		"""'default' enter sequence for state Erroneous.
		"""
		#'default' enter sequence for state Erroneous
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_erroneous()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_erroneous
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning_default(self):
		"""'default' enter sequence for state Malfunctioning.
		"""
		#'default' enter sequence for state Malfunctioning
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_malfunctioning()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_degraded_default(self):
		"""'default' enter sequence for state Degraded.
		"""
		#'default' enter sequence for state Degraded
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_degraded()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_degraded
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_failed_default(self):
		"""'default' enter sequence for state Failed.
		"""
		#'default' enter sequence for state Failed
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_failed()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_failed
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_default(self):
		"""'default' enter sequence for region Constituent Lifecycle.
		"""
		#'default' enter sequence for region Constituent Lifecycle
		self.__react_constituent_lifecycle__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_default(self):
		"""'default' enter sequence for region Belonging.
		"""
		#'default' enter sequence for region Belonging
		self.__react_constituent_lifecycle_orthogonal_states_belonging__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_default(self):
		"""'default' enter sequence for region Health.
		"""
		#'default' enter sequence for region Health
		self.__react_constituent_lifecycle_orthogonal_states_health__entry_default()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged(self):
		"""Default exit sequence for state Disengaged.
		"""
		#Default exit sequence for state Disengaged
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared(self):
		"""Default exit sequence for state Prepared.
		"""
		#Default exit sequence for state Prepared
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Default exit sequence for state Passive.
		"""
		#Default exit sequence for state Passive
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Default exit sequence for state Active.
		"""
		#Default exit sequence for state Active
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal(self):
		"""Default exit sequence for state Ideal.
		"""
		#Default exit sequence for state Ideal
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_defective(self):
		"""Default exit sequence for state Defective.
		"""
		#Default exit sequence for state Defective
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty(self):
		"""Default exit sequence for state Faulty.
		"""
		#Default exit sequence for state Faulty
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous(self):
		"""Default exit sequence for state Erroneous.
		"""
		#Default exit sequence for state Erroneous
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning(self):
		"""Default exit sequence for state Malfunctioning.
		"""
		#Default exit sequence for state Malfunctioning
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded(self):
		"""Default exit sequence for state Degraded.
		"""
		#Default exit sequence for state Degraded
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_failed(self):
		"""Default exit sequence for state Failed.
		"""
		#Default exit sequence for state Failed
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle(self):
		"""Default exit sequence for region Constituent Lifecycle.
		"""
		#Default exit sequence for region Constituent Lifecycle
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active()
		state = self.__state_vector[1]
		if state == self.State.constituent_lifecycle_orthogonal_states_health_ideal:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_defective:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_faulty:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_erroneous:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_degraded:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_failed:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_failed()
		
	def __react_constituent_lifecycle__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_default()
		
	def __react_constituent_lifecycle_orthogonal_states_belonging__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default()
		
	def __react_constituent_lifecycle_orthogonal_states_health__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
		
	def __constituent_lifecycle_orthogonal_states_belonging_disengaged_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_disengaged_react function.
		"""
		#The reactions of state Disengaged.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.prepare_for_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_prepared_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_prepared_react function.
		"""
		#The reactions of state Prepared.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.disengage_from_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default()
				transitioned_after = 0
			elif self.join_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_passive_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_passive_react function.
		"""
		#The reactions of state Passive.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.leave_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
			elif self.join_constellation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_active_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_active_react function.
		"""
		#The reactions of state Active.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.leave_constellation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_ideal_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_ideal_react function.
		"""
		#The reactions of state Ideal.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.component_deviation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_defective_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_defective_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_defective_react function.
		"""
		#The reactions of state Defective.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.defect_activated:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_faulty_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_faulty_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_faulty_react function.
		"""
		#The reactions of state Faulty.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.fault_exercised:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_erroneous_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_erroneous_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_erroneous_react function.
		"""
		#The reactions of state Erroneous.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.error_propogation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_malfunctioning_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_malfunctioning_react function.
		"""
		#The reactions of state Malfunctioning.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.service_impact_observed:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_degraded_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_degraded_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_degraded_react function.
		"""
		#The reactions of state Degraded.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.service_threshold_violated:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_failed_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_failed_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_failed_react function.
		"""
		#The reactions of state Failed.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_failed()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.prepare_for_so_s = False
		self.disengage_from_so_s = False
		self.join_so_s = False
		self.leave_so_s = False
		self.join_constellation = False
		self.leave_constellation = False
		self.recovery = False
		self.component_deviation = False
		self.defect_activated = False
		self.fault_exercised = False
		self.error_propogation = False
		self.service_impact_observed = False
		self.service_threshold_violated = False
	
	
	def __clear_internal_events(self):
		"""Implementation of __clear_internal_events function.
		"""
		self.health_changed = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		transitioned = -1
		self.__state_conf_vector_position = 0
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_disengaged_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_prepared_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_active_react(transitioned)
		if self.__state_conf_vector_position < 1:
			state = self.__state_vector[1]
			if state == self.State.constituent_lifecycle_orthogonal_states_health_ideal:
				self.__constituent_lifecycle_orthogonal_states_health_ideal_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_defective:
				self.__constituent_lifecycle_orthogonal_states_health_defective_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_faulty:
				self.__constituent_lifecycle_orthogonal_states_health_faulty_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_erroneous:
				self.__constituent_lifecycle_orthogonal_states_health_erroneous_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
				self.__constituent_lifecycle_orthogonal_states_health_malfunctioning_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_degraded:
				self.__constituent_lifecycle_orthogonal_states_health_degraded_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_failed:
				self.__constituent_lifecycle_orthogonal_states_health_failed_react(transitioned)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			self.__clear_internal_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart Statechart
		self.__enter_sequence_constituent_lifecycle_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart Statechart
		self.__exit_sequence_constituent_lifecycle()
		self.__state_vector[0] = self.State.null_state
		self.__state_vector[1] = self.State.null_state
		self.__state_conf_vector_position = 1
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
