"""Implementation of statechart statechart.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../src')))
from .yakindu.rx import Observable

class Statechart:
	"""Implementation of the state machine Statechart.
	"""

	class State:
		""" State Enum
		"""
		(
			constituent_lifecycle_orthogonal_states,
			constituent_lifecycle_orthogonal_states_belonging_disengaged,
			constituent_lifecycle_orthogonal_states_belonging_prepared,
			constituent_lifecycle_orthogonal_states_belonging_passive,
			constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating,
			constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable,
			constituent_lifecycle_orthogonal_states_belonging_active,
			constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry,
			constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit,
			constituent_lifecycle_orthogonal_states_belonging_active_region0participating,
			constituent_lifecycle_orthogonal_states_health_ideal,
			constituent_lifecycle_orthogonal_states_health_defective,
			constituent_lifecycle_orthogonal_states_health_faulty,
			constituent_lifecycle_orthogonal_states_health_erroneous,
			constituent_lifecycle_orthogonal_states_health_malfunctioning,
			constituent_lifecycle_orthogonal_states_health_degraded,
			constituent_lifecycle_orthogonal_states_health_failed,
			null_state
		) = range(18)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.prepare_for_so_s = None
		self.disengage_from_so_s = None
		self.join_so_s = None
		self.leave_so_s = None
		self.join_constellation = None
		self.leave_constellation = None
		self.exit_denied = None
		self.join_request = None
		self.join_invitation = None
		self.admission_rejected = None
		self.full_recovery = None
		self.degrade = None
		self.improve = None
		self.uncertainty_threshold_exceeded = None
		self.announce = None
		self.announce_value = None
		self.announce_observable = Observable()
		self.emit_observed = None
		self.emit_observed_value = None
		self.emit_observed_observable = Observable()
		self.emit_validated = None
		self.emit_validated_value = None
		self.emit_validated_observable = Observable()
		self.compensation_enabled = None
		self.compensation_enabled_value = None
		self.compensation_enabled_observable = Observable()
		self.belonging_changed = None
		self.belonging_changed_value = None
		self.belonging_changed_observable = Observable()
		self.health_changed = None
		self.health_changed_value = None
		self.health_changed_observable = Observable()
		
		self.in_event_queue = queue.Queue()
		self.DELTA = 1
		self.JS = "join_SoS"
		self.LS = "leave_SoS"
		self.JC = "join_constellation"
		self.LC = "leave_constellation"
		self.LI = "leave_initated"
		self.DISENGAGED = "disengaged"
		self.PREPARED = "prepared"
		self.AVAILABLE = "available"
		self.NEGOTIATING = "negotiating"
		self.PENDING_ENTRY = "pending_entry"
		self.PENDING_EXIT = "pending_exit"
		self.IDEAL = "ideal"
		self.DEFECTIVE = "defective"
		self.FAULTY = "faulty"
		self.ERRONEOUS = "erroneous"
		self.MALFUNCTIONING = "malfunctioning"
		self.DEGRADED = "degraded"
		self.FAILED = "failed"
		
		# enumeration of all states:
		self.__State = Statechart.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 2
		for __state_index in range(2):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 2
		
		# initializations:
		self.__is_executing = False
		self.__state_conf_vector_position = None
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.constituent_lifecycle_orthogonal_states:
			return (self.__state_vector[0] >= self.__State.constituent_lifecycle_orthogonal_states)\
				and (self.__state_vector[0] <= self.__State.constituent_lifecycle_orthogonal_states_health_failed)
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_disengaged
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_prepared
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive:
			return (self.__state_vector[0] >= self.__State.constituent_lifecycle_orthogonal_states_belonging_passive)\
				and (self.__state_vector[0] <= self.__State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable)
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_active:
			return (self.__state_vector[0] >= self.__State.constituent_lifecycle_orthogonal_states_belonging_active)\
				and (self.__state_vector[0] <= self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating)
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit
		if s == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating:
			return self.__state_vector[0] == self.__State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_ideal:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_ideal
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_defective:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_defective
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_faulty:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_faulty
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_erroneous:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_erroneous
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_malfunctioning
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_degraded:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_degraded
		if s == self.__State.constituent_lifecycle_orthogonal_states_health_failed:
			return self.__state_vector[1] == self.__State.constituent_lifecycle_orthogonal_states_health_failed
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(2):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_prepare_for_so_s(self):
		"""Raise method for event prepare_for_so_s.
		"""
		self.in_event_queue.put(self.__raise_prepare_for_so_s_call)
		self.run_cycle()
	
	def __raise_prepare_for_so_s_call(self):
		"""Raise callback for event prepare_for_so_s.
		"""
		self.prepare_for_so_s = True
	
	def raise_disengage_from_so_s(self):
		"""Raise method for event disengage_from_so_s.
		"""
		self.in_event_queue.put(self.__raise_disengage_from_so_s_call)
		self.run_cycle()
	
	def __raise_disengage_from_so_s_call(self):
		"""Raise callback for event disengage_from_so_s.
		"""
		self.disengage_from_so_s = True
	
	def raise_join_so_s(self):
		"""Raise method for event join_so_s.
		"""
		self.in_event_queue.put(self.__raise_join_so_s_call)
		self.run_cycle()
	
	def __raise_join_so_s_call(self):
		"""Raise callback for event join_so_s.
		"""
		self.join_so_s = True
	
	def raise_leave_so_s(self):
		"""Raise method for event leave_so_s.
		"""
		self.in_event_queue.put(self.__raise_leave_so_s_call)
		self.run_cycle()
	
	def __raise_leave_so_s_call(self):
		"""Raise callback for event leave_so_s.
		"""
		self.leave_so_s = True
	
	def raise_join_constellation(self):
		"""Raise method for event join_constellation.
		"""
		self.in_event_queue.put(self.__raise_join_constellation_call)
		self.run_cycle()
	
	def __raise_join_constellation_call(self):
		"""Raise callback for event join_constellation.
		"""
		self.join_constellation = True
	
	def raise_leave_constellation(self):
		"""Raise method for event leave_constellation.
		"""
		self.in_event_queue.put(self.__raise_leave_constellation_call)
		self.run_cycle()
	
	def __raise_leave_constellation_call(self):
		"""Raise callback for event leave_constellation.
		"""
		self.leave_constellation = True
	
	def raise_exit_denied(self):
		"""Raise method for event exit_denied.
		"""
		self.in_event_queue.put(self.__raise_exit_denied_call)
		self.run_cycle()
	
	def __raise_exit_denied_call(self):
		"""Raise callback for event exit_denied.
		"""
		self.exit_denied = True
	
	def raise_join_request(self):
		"""Raise method for event join_request.
		"""
		self.in_event_queue.put(self.__raise_join_request_call)
		self.run_cycle()
	
	def __raise_join_request_call(self):
		"""Raise callback for event join_request.
		"""
		self.join_request = True
	
	def raise_join_invitation(self):
		"""Raise method for event join_invitation.
		"""
		self.in_event_queue.put(self.__raise_join_invitation_call)
		self.run_cycle()
	
	def __raise_join_invitation_call(self):
		"""Raise callback for event join_invitation.
		"""
		self.join_invitation = True
	
	def raise_admission_rejected(self):
		"""Raise method for event admission_rejected.
		"""
		self.in_event_queue.put(self.__raise_admission_rejected_call)
		self.run_cycle()
	
	def __raise_admission_rejected_call(self):
		"""Raise callback for event admission_rejected.
		"""
		self.admission_rejected = True
	
	def raise_full_recovery(self):
		"""Raise method for event full_recovery.
		"""
		self.in_event_queue.put(self.__raise_full_recovery_call)
		self.run_cycle()
	
	def __raise_full_recovery_call(self):
		"""Raise callback for event full_recovery.
		"""
		self.full_recovery = True
	
	def raise_degrade(self):
		"""Raise method for event degrade.
		"""
		self.in_event_queue.put(self.__raise_degrade_call)
		self.run_cycle()
	
	def __raise_degrade_call(self):
		"""Raise callback for event degrade.
		"""
		self.degrade = True
	
	def raise_improve(self):
		"""Raise method for event improve.
		"""
		self.in_event_queue.put(self.__raise_improve_call)
		self.run_cycle()
	
	def __raise_improve_call(self):
		"""Raise callback for event improve.
		"""
		self.improve = True
	
	def raise_uncertainty_threshold_exceeded(self):
		"""Raise method for event uncertainty_threshold_exceeded.
		"""
		self.in_event_queue.put(self.__raise_uncertainty_threshold_exceeded_call)
		self.run_cycle()
	
	def __raise_uncertainty_threshold_exceeded_call(self):
		"""Raise callback for event uncertainty_threshold_exceeded.
		"""
		self.uncertainty_threshold_exceeded = True
	
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_disengaged(self):
		"""Entry action for state 'Disengaged'..
		"""
		#Entry action for state 'Disengaged'.
		self.belonging_changed_observable.next(self.DISENGAGED)
		self.emit_observed_observable.next(False)
		self.emit_validated_observable.next(False)
		self.compensation_enabled_observable.next(False)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_prepared(self):
		"""Entry action for state 'Prepared'..
		"""
		#Entry action for state 'Prepared'.
		self.belonging_changed_observable.next(self.PREPARED)
		self.emit_observed_observable.next(False)
		self.emit_validated_observable.next(False)
		self.compensation_enabled_observable.next(False)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Entry action for state 'Passive'..
		"""
		#Entry action for state 'Passive'.
		self.announce_observable.next(self.JS)
		self.emit_observed_observable.next(True)
		self.emit_validated_observable.next(False)
		self.compensation_enabled_observable.next(False)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating(self):
		"""Entry action for state 'Negotiating'..
		"""
		#Entry action for state 'Negotiating'.
		self.belonging_changed_observable.next(self.NEGOTIATING)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable(self):
		"""Entry action for state 'Avaliable'..
		"""
		#Entry action for state 'Avaliable'.
		self.belonging_changed_observable.next(self.AVAILABLE)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Entry action for state 'Active'..
		"""
		#Entry action for state 'Active'.
		self.announce_observable.next(self.JC)
		self.emit_observed_observable.next(True)
		self.emit_validated_observable.next(False)
		self.compensation_enabled_observable.next(False)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry(self):
		"""Entry action for state 'Pending Entry'..
		"""
		#Entry action for state 'Pending Entry'.
		self.timer_service.set_timer(self, 0, (self.DELTA * 1000), False)
		self.belonging_changed_observable.next(self.PENDING_ENTRY)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit(self):
		"""Entry action for state 'Pending Exit'..
		"""
		#Entry action for state 'Pending Exit'.
		self.timer_service.set_timer(self, 1, (self.DELTA * 1000), False)
		self.belonging_changed_observable.next(self.PENDING_EXIT)
		self.emit_validated_observable.next(False)
		self.compensation_enabled_observable.next(False)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating(self):
		"""Entry action for state 'Participating'..
		"""
		#Entry action for state 'Participating'.
		self.emit_validated_observable.next(True)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_ideal(self):
		"""Entry action for state 'Ideal'..
		"""
		#Entry action for state 'Ideal'.
		self.health_changed_observable.next(self.IDEAL)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_defective(self):
		"""Entry action for state 'Defective'..
		"""
		#Entry action for state 'Defective'.
		self.health_changed_observable.next(self.DEFECTIVE)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_faulty(self):
		"""Entry action for state 'Faulty'..
		"""
		#Entry action for state 'Faulty'.
		self.health_changed_observable.next(self.FAULTY)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_erroneous(self):
		"""Entry action for state 'Erroneous'..
		"""
		#Entry action for state 'Erroneous'.
		self.health_changed_observable.next(self.ERRONEOUS)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_malfunctioning(self):
		"""Entry action for state 'Malfunctioning'..
		"""
		#Entry action for state 'Malfunctioning'.
		self.health_changed_observable.next(self.MALFUNCTIONING)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_degraded(self):
		"""Entry action for state 'Degraded'..
		"""
		#Entry action for state 'Degraded'.
		self.health_changed_observable.next(self.DEGRADED)
		
	def __entry_action_constituent_lifecycle_orthogonal_states_health_failed(self):
		"""Entry action for state 'Failed'..
		"""
		#Entry action for state 'Failed'.
		self.health_changed_observable.next(self.FAILED)
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Exit action for state 'Passive'..
		"""
		#Exit action for state 'Passive'.
		self.announce_observable.next(self.LS)
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Exit action for state 'Active'..
		"""
		#Exit action for state 'Active'.
		self.announce_observable.next(self.LC)
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry(self):
		"""Exit action for state 'Pending Entry'..
		"""
		#Exit action for state 'Pending Entry'.
		self.timer_service.unset_timer(self, 0)
		
	def __exit_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit(self):
		"""Exit action for state 'Pending Exit'..
		"""
		#Exit action for state 'Pending Exit'.
		self.timer_service.unset_timer(self, 1)
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_default(self):
		"""'default' enter sequence for state Orthogonal States.
		"""
		#'default' enter sequence for state Orthogonal States
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_default()
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default(self):
		"""'default' enter sequence for state Disengaged.
		"""
		#'default' enter sequence for state Disengaged
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_disengaged()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default(self):
		"""'default' enter sequence for state Prepared.
		"""
		#'default' enter sequence for state Prepared
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_prepared()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_prepared
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default(self):
		"""'default' enter sequence for state Passive.
		"""
		#'default' enter sequence for state Passive
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_default(self):
		"""'default' enter sequence for state Negotiating.
		"""
		#'default' enter sequence for state Negotiating
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_default(self):
		"""'default' enter sequence for state Avaliable.
		"""
		#'default' enter sequence for state Avaliable
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active_default(self):
		"""'default' enter sequence for state Active.
		"""
		#'default' enter sequence for state Active
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_active()
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry_default(self):
		"""'default' enter sequence for state Pending Entry.
		"""
		#'default' enter sequence for state Pending Entry
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_default(self):
		"""'default' enter sequence for state Pending Exit.
		"""
		#'default' enter sequence for state Pending Exit
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_default(self):
		"""'default' enter sequence for state Participating.
		"""
		#'default' enter sequence for state Participating
		self.__entry_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default(self):
		"""'default' enter sequence for state Ideal.
		"""
		#'default' enter sequence for state Ideal
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_ideal()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_ideal
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_defective_default(self):
		"""'default' enter sequence for state Defective.
		"""
		#'default' enter sequence for state Defective
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_defective()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_defective
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_faulty_default(self):
		"""'default' enter sequence for state Faulty.
		"""
		#'default' enter sequence for state Faulty
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_faulty()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_faulty
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_erroneous_default(self):
		"""'default' enter sequence for state Erroneous.
		"""
		#'default' enter sequence for state Erroneous
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_erroneous()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_erroneous
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning_default(self):
		"""'default' enter sequence for state Malfunctioning.
		"""
		#'default' enter sequence for state Malfunctioning
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_malfunctioning()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_degraded_default(self):
		"""'default' enter sequence for state Degraded.
		"""
		#'default' enter sequence for state Degraded
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_degraded()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_degraded
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_failed_default(self):
		"""'default' enter sequence for state Failed.
		"""
		#'default' enter sequence for state Failed
		self.__entry_action_constituent_lifecycle_orthogonal_states_health_failed()
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states_health_failed
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_constituent_lifecycle_default(self):
		"""'default' enter sequence for region Constituent Lifecycle.
		"""
		#'default' enter sequence for region Constituent Lifecycle
		self.__react_constituent_lifecycle__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_default(self):
		"""'default' enter sequence for region Belonging.
		"""
		#'default' enter sequence for region Belonging
		self.__react_constituent_lifecycle_orthogonal_states_belonging__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_default(self):
		"""'default' enter sequence for region null.
		"""
		#'default' enter sequence for region null
		self.__react_constituent_lifecycle_orthogonal_states_belonging_passive__region0__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_default(self):
		"""'default' enter sequence for region null.
		"""
		#'default' enter sequence for region null
		self.__react_constituent_lifecycle_orthogonal_states_belonging_active__region0__entry_default()
		
	def __enter_sequence_constituent_lifecycle_orthogonal_states_health_default(self):
		"""'default' enter sequence for region Health.
		"""
		#'default' enter sequence for region Health
		self.__react_constituent_lifecycle_orthogonal_states_health__entry_default()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged(self):
		"""Default exit sequence for state Disengaged.
		"""
		#Default exit sequence for state Disengaged
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared(self):
		"""Default exit sequence for state Prepared.
		"""
		#Default exit sequence for state Prepared
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive(self):
		"""Default exit sequence for state Passive.
		"""
		#Default exit sequence for state Passive
		self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating(self):
		"""Default exit sequence for state Negotiating.
		"""
		#Default exit sequence for state Negotiating
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_passive
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable(self):
		"""Default exit sequence for state Avaliable.
		"""
		#Default exit sequence for state Avaliable
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_passive
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active(self):
		"""Default exit sequence for state Active.
		"""
		#Default exit sequence for state Active
		self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0()
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry(self):
		"""Default exit sequence for state Pending Entry.
		"""
		#Default exit sequence for state Pending Entry
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit(self):
		"""Default exit sequence for state Pending Exit.
		"""
		#Default exit sequence for state Pending Exit
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active
		self.__state_conf_vector_position = 0
		self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating(self):
		"""Default exit sequence for state Participating.
		"""
		#Default exit sequence for state Participating
		self.__state_vector[0] = self.State.constituent_lifecycle_orthogonal_states_belonging_active
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal(self):
		"""Default exit sequence for state Ideal.
		"""
		#Default exit sequence for state Ideal
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_defective(self):
		"""Default exit sequence for state Defective.
		"""
		#Default exit sequence for state Defective
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty(self):
		"""Default exit sequence for state Faulty.
		"""
		#Default exit sequence for state Faulty
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous(self):
		"""Default exit sequence for state Erroneous.
		"""
		#Default exit sequence for state Erroneous
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning(self):
		"""Default exit sequence for state Malfunctioning.
		"""
		#Default exit sequence for state Malfunctioning
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded(self):
		"""Default exit sequence for state Degraded.
		"""
		#Default exit sequence for state Degraded
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_health_failed(self):
		"""Default exit sequence for state Failed.
		"""
		#Default exit sequence for state Failed
		self.__state_vector[1] = self.State.constituent_lifecycle_orthogonal_states
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_constituent_lifecycle(self):
		"""Default exit sequence for region Constituent Lifecycle.
		"""
		#Default exit sequence for region Constituent Lifecycle
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating()
			self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable()
			self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_passive()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
			self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit()
			self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating()
			self.__exit_action_constituent_lifecycle_orthogonal_states_belonging_active()
		state = self.__state_vector[1]
		if state == self.State.constituent_lifecycle_orthogonal_states_health_ideal:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_defective:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_faulty:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_erroneous:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_degraded:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
		elif state == self.State.constituent_lifecycle_orthogonal_states_health_failed:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_failed()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0(self):
		"""Default exit sequence for region null.
		"""
		#Default exit sequence for region null
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable()
		
	def __exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0(self):
		"""Default exit sequence for region null.
		"""
		#Default exit sequence for region null
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit()
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating:
			self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating()
		
	def __react_constituent_lifecycle__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_default()
		
	def __react_constituent_lifecycle_orthogonal_states_belonging__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default()
		
	def __react_constituent_lifecycle_orthogonal_states_belonging_passive__region0__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_default()
		
	def __react_constituent_lifecycle_orthogonal_states_belonging_active__region0__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry_default()
		
	def __react_constituent_lifecycle_orthogonal_states_health__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
		
	def __constituent_lifecycle_orthogonal_states_belonging_disengaged_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_disengaged_react function.
		"""
		#The reactions of state Disengaged.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.prepare_for_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_prepared_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_prepared_react function.
		"""
		#The reactions of state Prepared.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.disengage_from_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_disengaged_default()
				transitioned_after = 0
			elif (self.join_so_s) and (not (self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_failed)):
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_passive_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_passive_react function.
		"""
		#The reactions of state Passive.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_failed):
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
			elif self.leave_so_s:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_react function.
		"""
		#The reactions of state Negotiating.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.admission_rejected:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(0)
				transitioned_after = 0
			elif self.join_constellation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active_default()
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(transitioned_before)
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_react function.
		"""
		#The reactions of state Avaliable.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.join_request) and ((self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_ideal)):
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(0)
				transitioned_after = 0
			elif (self.join_invitation) and ((self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_ideal) or (self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_defective) or (self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_faulty)):
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__constituent_lifecycle_orthogonal_states_belonging_passive_react(transitioned_before)
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_active_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_active_react function.
		"""
		#The reactions of state Active.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if (self.__state_vector[1] == self.State.constituent_lifecycle_orthogonal_states_health_failed):
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_prepared_default()
				transitioned_after = 0
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry_react function.
		"""
		#The reactions of state Pending Entry.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.leave_constellation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
				self.announce_observable.next(self.LI)
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_active_react(0)
				transitioned_after = 0
			elif self.__time_events[0]:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry()
				self.__time_events[0] = False
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_active_react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__constituent_lifecycle_orthogonal_states_belonging_active_react(transitioned_before)
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_react function.
		"""
		#The reactions of state Pending Exit.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.__time_events[1]:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active()
				self.__time_events[1] = False
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_passive_default()
				transitioned_after = 0
			elif self.exit_denied:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_active_react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__constituent_lifecycle_orthogonal_states_belonging_active_react(transitioned_before)
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_react function.
		"""
		#The reactions of state Participating.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.leave_constellation:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_participating()
				self.announce_observable.next(self.LI)
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_default()
				self.__constituent_lifecycle_orthogonal_states_belonging_active_react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__constituent_lifecycle_orthogonal_states_belonging_active_react(transitioned_before)
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_ideal_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_ideal_react function.
		"""
		#The reactions of state Ideal.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_ideal()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_defective_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_defective_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_defective_react function.
		"""
		#The reactions of state Defective.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_faulty_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_defective()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_faulty_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_faulty_react function.
		"""
		#The reactions of state Faulty.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_erroneous_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_faulty()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_defective_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_erroneous_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_erroneous_react function.
		"""
		#The reactions of state Erroneous.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_erroneous()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_faulty_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_malfunctioning_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_malfunctioning_react function.
		"""
		#The reactions of state Malfunctioning.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_degraded_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_erroneous_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_degraded_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_degraded_react function.
		"""
		#The reactions of state Degraded.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.degrade:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_failed_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_degraded()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_malfunctioning_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __constituent_lifecycle_orthogonal_states_health_failed_react(self, transitioned_before):
		"""Implementation of __constituent_lifecycle_orthogonal_states_health_failed_react function.
		"""
		#The reactions of state Failed.
		transitioned_after = transitioned_before
		if transitioned_after < 1:
			if self.full_recovery:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_failed()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_ideal_default()
				transitioned_after = 1
			elif self.improve:
				self.__exit_sequence_constituent_lifecycle_orthogonal_states_health_failed()
				self.__enter_sequence_constituent_lifecycle_orthogonal_states_health_degraded_default()
				transitioned_after = 1
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = transitioned_before
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.prepare_for_so_s = False
		self.disengage_from_so_s = False
		self.join_so_s = False
		self.leave_so_s = False
		self.join_constellation = False
		self.leave_constellation = False
		self.exit_denied = False
		self.join_request = False
		self.join_invitation = False
		self.admission_rejected = False
		self.full_recovery = False
		self.degrade = False
		self.improve = False
		self.uncertainty_threshold_exceeded = False
		self.__time_events[0] = False
		self.__time_events[1] = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		transitioned = -1
		self.__state_conf_vector_position = 0
		state = self.__state_vector[0]
		if state == self.State.constituent_lifecycle_orthogonal_states_belonging_disengaged:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_disengaged_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_prepared:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_prepared_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0negotiating:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_passive__region0_negotiating_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_passive_region0avaliable:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_passive__region0_avaliable_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_entry:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_entry_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0pending_exit:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_active__region0_pending_exit_react(transitioned)
		elif state == self.State.constituent_lifecycle_orthogonal_states_belonging_active_region0participating:
			transitioned = self.__constituent_lifecycle_orthogonal_states_belonging_active__region0_participating_react(transitioned)
		if self.__state_conf_vector_position < 1:
			state = self.__state_vector[1]
			if state == self.State.constituent_lifecycle_orthogonal_states_health_ideal:
				self.__constituent_lifecycle_orthogonal_states_health_ideal_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_defective:
				self.__constituent_lifecycle_orthogonal_states_health_defective_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_faulty:
				self.__constituent_lifecycle_orthogonal_states_health_faulty_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_erroneous:
				self.__constituent_lifecycle_orthogonal_states_health_erroneous_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_malfunctioning:
				self.__constituent_lifecycle_orthogonal_states_health_malfunctioning_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_degraded:
				self.__constituent_lifecycle_orthogonal_states_health_degraded_react(transitioned)
			elif state == self.State.constituent_lifecycle_orthogonal_states_health_failed:
				self.__constituent_lifecycle_orthogonal_states_health_failed_react(transitioned)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart Statechart
		self.__enter_sequence_constituent_lifecycle_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart Statechart
		self.__exit_sequence_constituent_lifecycle()
		self.__state_vector[0] = self.State.null_state
		self.__state_vector[1] = self.State.null_state
		self.__state_conf_vector_position = 1
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
